kind: pipeline
type: docker
name: atlas

steps:
  - name: docker_atlas_raw
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      registry: quay.io
      repo: quay.io/heetch/atlas
      tags: atlas-raw-release-2.1.0-rc3
      username:
        from_secret: org_quay_username
      password:
        from_secret: org_quay_password
    when:
      event: push
      branch:
        - heetch-atlas-release-2.1.0-rc3

  - name: docker_atlas_raw_release
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      registry: quay.io
      repo: quay.io/heetch/atlas
      auto_tag_suffix: atlas-raw
      auto_tag: true
      username:
        from_secret: org_quay_username
      password:
        from_secret: org_quay_password
    when:
      event: tag

  - name: docker_atlas_embedded_hbase_solr
    image: plugins/docker
    settings:
      build_args:
        - PROFILE=-Pdist,embedded-hbase-solr
      dockerfile: Dockerfile
      registry: quay.io
      repo: quay.io/heetch/atlas
      tags: atlas-embedded-hbase-solr-release-2.1.0-rc3
      username:
        from_secret: org_quay_username
      password:
        from_secret: org_quay_password
    when:
      event: push
      branch:
        - heetch-atlas-release-2.1.0-rc3

  - name: docker_atlas_embedded_hbase_solr_release
    image: plugins/docker
    settings:
      build_args:
        - PROFILE=-Pdist,embedded-hbase-solr
      dockerfile: Dockerfile
      registry: quay.io
      repo: quay.io/heetch/atlas
      auto_tag_suffix: atlas-embedded-hbase-solr
      auto_tag: true
      username:
        from_secret: org_quay_username
      password:
        from_secret: org_quay_password
    when:
      event: tag