kind: pipeline
type: docker
name: atlas

steps:
  - name: docker_atlas_raw_release
    image: plugins/ecr
    settings:
      dockerfile: Dockerfile
      registry: 074232677442.dkr.ecr.us-east-1.amazonaws.com
      repo: atlas
      tags: ${DRONE_TAG}-atlas-raw

    when:
      event: tag

  - name: docker_atlas_embedded_hbase_solr_release
    image: plugins/ecr
    settings:
      build_args:
        - PROFILE=-Pdist,embedded-hbase-solr
      dockerfile: Dockerfile
      registry: 074232677442.dkr.ecr.us-east-1.amazonaws.com
      repo: atlas
      tags: ${DRONE_TAG}-atlas-embedded-hbase-solr
    when:
      event: tag