kind: pipeline
type: docker
name: atlas

steps:
  - name: docker_atlas_raw
    image: plugins/ecr
    settings:
      dockerfile: Dockerfile
      tags: atlas-raw-release-2.1.0-rc3
      repo: atlas
      registry: 074232677442.dkr.ecr.us-east-1.amazonaws.com
      access_key:
        from_secret: org_ecr_access_key
      secret_key:
        from_secret: org_ecr_secret_key
    when:
      event: push
      branch:
        - heetch-atlas-release-2.1.0-rc3

  - name: docker_atlas_raw_release
    image: plugins/ecr
    settings:
      dockerfile: Dockerfile
      registry: 074232677442.dkr.ecr.us-east-1.amazonaws.com
      repo: atlas
      auto_tag_suffix: atlas-raw
      auto_tag: true
      access_key:
        from_secret: org_ecr_access_key
      secret_key:
        from_secret: org_ecr_secret_key
    when:
      event: tag

  - name: docker_atlas_embedded_hbase_solr
    image: plugins/ecr
    settings:
      build_args:
        - PROFILE=-Pdist,embedded-hbase-solr
      dockerfile: Dockerfile
      registry: 074232677442.dkr.ecr.us-east-1.amazonaws.com
      repo: atlas
      tags: atlas-embedded-hbase-solr-release-2.1.0-rc3
      access_key:
        from_secret: org_ecr_access_key
      secret_key:
        from_secret: org_ecr_secret_key
    when:
      event: push
      branch:
        - heetch-atlas-release-2.1.0-rc3

  - name: docker_atlas_embedded_hbase_solr_release
    image: plugins/ecr
    settings:
      build_args:
        - PROFILE=-Pdist,embedded-hbase-solr
      dockerfile: Dockerfile
      registry: 074232677442.dkr.ecr.us-east-1.amazonaws.com
      repo: atlas
      auto_tag_suffix: atlas-embedded-hbase-solr
      auto_tag: true
      access_key:
        from_secret: org_ecr_access_key
      secret_key:
        from_secret: org_ecr_secret_key
    when:
      event: tag