steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/datapoc-440217/apache-atlas:latest', '.']
images:
  - 'gcr.io/datapoc-440217/apache-atlas:latest'

options:
  logging: CLOUD_LOGGING_ONLY  # Isso envia os logs para o Cloud Logging
